weights: yolov5s.pt
cfg: ./models/sP5.yaml
data: ./nia_utils/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 200
batch_size: 64
imgsz: 224
device: '0'
adam: false
workers: 8
project: ./runs/train
name: s3
label_smoothing: 0.0
patience: 100
save_dir: runs/train/s3
